<a href="https://colab.research.google.com/github/Zidane86-06/Data_Engineering_workshop/blob/main/Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
df=pd.read_csv('student_performance.csv')

In [4]:
print(df)

    student_id            name  age  gender        department  semester  \
0         1001    Aarav Sharma   19    Male  Computer Science         2
1         1002     Priya Patel   20  Female  Computer Science         2
2         1003     Rohit Verma   19    Male       Electronics         2
3         1004     Sneha Reddy   20  Female        Mechanical         2
4         1005      Arjun Nair   19    Male  Computer Science         2
5         1006     Meera Joshi   20  Female       Electronics         2
6         1007     Kiran Kumar   21    Male             Civil         2
7         1008     Divya Singh   19  Female  Computer Science         2
8         1009    Rahul Mishra   20    Male        Mechanical         2
9         1010      Ananya Das   19  Female  Computer Science         2
10        1011     Vikram Iyer   20    Male       Electronics         2
11        1012     Pooja Gupta   19  Female             Civil         2
12        1013      Suresh Rao   21    Male  Computer Science         2
13        1014   Kavya Nambiar   20  Female        Mechanical         2
14        1015     Ajay Tiwari   19    Male  Computer Science         2
15        1016    Ritu Agarwal   20  Female       Electronics         2
16        1017    Manoj Pandey   21    Male             Civil         2
17        1018  Swati Kulkarni   19  Female  Computer Science         2
18        1019  Deepak Chauhan   20    Male        Mechanical         2
19        1020    Nisha Kapoor   19  Female  Computer Science         2
20        1021   Harish Pillai   20    Male       Electronics         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
22        1023    Sanjay Dubey   21    Male             Civil         2
23        1024   Preeti Saxena   20  Female        Mechanical         2
24        1025       Amit Bose   19    Male  Computer Science         2
25        1026      Rekha Nair   20  Female       Electronics         2
26        1027   Gaurav Shukla   21    Male  Computer Science         2
27        1028   Sunita Pillai   19  Female             Civil         2
28        1029      Nitin Jain   20    Male        Mechanical         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
0           85             78             72                 91
1           76             82             88                 79
2           65             74             61                 55
3           70             80             75                 48
4           92             88             81                 95
5           58             66             70                 52
6           73             69             65                 40
7           88             91             84                 93
8           62             71             58                 45
9           95             89             90                 97
10          80             75             68                 72
11          67             72             79                 44
12          83             86             77                 88
13          74             78             82                 51
14          71             69             64                 76
15          87             83             86                 69
16          56             61             55                 38
17          90             87             85                 92
18          68             73             62                 49
19          79             84             81                 83
20          64             70             67                 58
21          93             90             88                 96
22          61             66             59                 42
23          77             81             76                 53
24          86             82             79                 89
25          72             77             73                 63
26          84             79             75                 87
27          60             65             68                 39
28          75             76             70                 50
29          91             93             87                 94

    attendance_percentage                city  admission_year
0                      92              Mumbai            2023
1                      87           Ahmedabad            2023
2                      78               Delhi            2023
3                      95           Hyderabad            2023
4                      90               Kochi            2023
5                      72                Pune            2023
6                      85           Bangalore            2023
7                      96             Lucknow            2023
8                      68            Varanasi            2023
9                      98             Kolkata            2023
10                     83             Chennai            2023
11                     80              Jaipur            2023
12                     88              Mysore            2023
13                     91            Thrissur            2023
14                     75              Bhopal            2023
15                     93                Agra            2023
16                     65               Patna            2023
17                     94              Nagpur            2023
18                     77            Dehradun            2023
19                     89          Chandigarh            2023
20                     74  Thiruvananthapuram            2023
21                     97               Surat            2023
22                     70           Allahabad            2023
23                     86              Kanpur            2023
24                     91             Kolkata            2023
25                     82               Kochi            2023
26                     87             Lucknow            2023
27                     73  Thiruvananthapuram            2023
28                     84              Indore            2023
29                     95                Agra            2023

In [5]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [6]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [7]:
print("Shape of dataset:",df.shape)
print("Number of students:",df.shape[0])
print("Number of coloumns:",df.shape[1])

Shape of dataset: (30, 13)
Number of students: 30
Number of coloumns: 13

In [9]:
print("Columns in the dataaset:")
print(df.columns.tolist())

Columns in the dataaset:
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [11]:
print("Data Types:")
print(df.dtypes)

Data Types:
student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [12]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [15]:
print("Missing values in each column:")
print(df.isnull().sum())
print("\nTotal missing values:",df.isnull().sum().sum())

Missing values in each column:
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

Total missing values: 0

In [16]:
print("Student Name:")
print(df['name'])

Student Name:
0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [19]:
print("Departments in this dataset:")
print(df['department'].unique())

print('\nHow many students per department:')
print(df['department'].value_counts())

Departments in this dataset:
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

How many students per department:
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [20]:
cs_students=df[df['department']=='Computer Science']
print(f"Number of Computer Science students:{len(cs_students)}")
print("\nComputer Science Students:")
print(cs_students[['name','math_score','programming_score','attendance_percentage']])

Number of Computer Science students:13

Computer Science Students:
              name  math_score  programming_score  attendance_percentage
0     Aarav Sharma          85                 91                     92
1      Priya Patel          76                 79                     87
4       Arjun Nair          92                 95                     90
7      Divya Singh          88                 93                     96
9       Ananya Das          95                 97                     98
12      Suresh Rao          83                 88                     88
14     Ajay Tiwari          71                 76                     75
17  Swati Kulkarni          90                 92                     94
19    Nisha Kapoor          79                 83                     89
21     Tanvi Mehta          93                 96                     97
24       Amit Bose          86                 89                     91
26   Gaurav Shukla          84                 87                     87
29  Akanksha Yadav          91                 94                     95

In [21]:
cs_high_attendance_students=df[(df['attendance_percentage']>90)&(df['department']=='Computer Science')]
print(f"Number of Computer Science students with attendance greater than 90%:{len(cs_high_attendance_students)}")
display(cs_high_attendance_students[['name','department','attendance_percentage']])

Number of Computer Science students with attendance greater than 90%:7

              name        department  attendance_percentage
0     Aarav Sharma  Computer Science                     92
7      Divya Singh  Computer Science                     96
9       Ananya Das  Computer Science                     98
17  Swati Kulkarni  Computer Science                     94
21     Tanvi Mehta  Computer Science                     97
24       Amit Bose  Computer Science                     91
29  Akanksha Yadav  Computer Science                     95

In [22]:
df['average_score'] = df[['math_score', 'science_score', 'english_score', 'programming_score']].mean(axis=1)
display(df.head())

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year,average_score
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023,81.50
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023,81.25
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023,63.75
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023,68.25
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023,89.00

In [23]:
top_students_per_department = df.groupby('department').apply(lambda x: x.nlargest(3, 'average_score')).reset_index(drop=True)
print("Top 3 performing students in each department:")
display(top_students_per_department[['name', 'department', 'average_score']])

Top 3 performing students in each department:

/tmp/ipykernel_3923/3920932040.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top_students_per_department = df.groupby('department').apply(lambda x: x.nlargest(3, 'average_score')).reset_index(drop=True)

              name        department  average_score
0      Pooja Gupta             Civil          65.50
1      Kiran Kumar             Civil          61.75
2    Sunita Pillai             Civil          58.00
3       Ananya Das  Computer Science          92.75
4      Tanvi Mehta  Computer Science          91.75
5   Akanksha Yadav  Computer Science          91.25
6     Ritu Agarwal       Electronics          81.25
7      Vikram Iyer       Electronics          73.75
8       Rekha Nair       Electronics          71.25
9    Preeti Saxena        Mechanical          71.75
10   Kavya Nambiar        Mechanical          71.25
11     Sneha Reddy        Mechanical          68.25

In [33]:
average_score_per_department = df.groupby('department')['average_score'].mean().reset_index()
print("Average score per department:")
display(average_score_per_department.sort_values(by='average_score', ascending=False))

Average score per department:

         department  average_score
1  Computer Science      85.038462
2       Electronics      69.375000
3        Mechanical      66.833333
0             Civil      58.950000